name: concurrency test 1

on:
  workflow_dispatch:

# Workflow level concurrency 

concurrency:
  group: test1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ—ï¸ Building..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ Deploying..."
